name: Backfill TAL Episodes

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  backfill:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Run backfill
        run: python backfill.py

      - name: Commit & push updated CSV
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add tal_episodes_full.csv
          git diff --quiet && git diff --staged --quiet || git commit -m "Backfill episode descriptions"
          git push https://x-access-to
