name: Scrape TAL RSS

on:
  push:
    branches:
      - main
#  schedule:       # Uncomment to enable daily schedule
#    - cron: '0 6 * * *'  # Runs daily at 06:00 UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Run scraper
        run: python scrape_feed.py

      - name: Commit CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add tal_episodes.csv
          git commit -m "Update TAL episodes CSV" || echo "No changes to commit"
          git push
